[author]
  name = "xHain hack+makespace"
  picture = "images/global/xhain_logo_small.png"
  twitter = "xHain_hackspace"
  #gravatarEmail = "info@x-hain.de"

[params]
  dateFormat = "2. January 2006"
  clearReading = true
  hierarchicalCategories = true
  sidebarBehavior = 1
  coverImage = "global/background-cover.jpg"
  imageGallery = true
  thumbnailImage = true
  thumbnailImagePosition = "right"
  autoThumbnailImage = true
  favicon = "images/favicons/"
  copyright = ""
  #archivePagination = true
  #categoryPagination = true
  #tagPagination = true

# Enable or disable social icons
[params.social]
  enable = false