baseurl = "https://staging.x-hain.de"
title = "xHain hack+makespace"
canonifyurls = true
languageCode = "de"
defaultContentLanguage = "de"
DefaultContentLanguageInSubdir = "true"
MetaDataFormat = "yaml"

disableLanguageSwitchingButton = true

# Define the number of posts per page
paginate = 6

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  viewMorePostLink = "/blog/"
  author = "Webteam"
  defaultKeywords = ["hackspace", "makerspace", "xhain"]
  defaultDescription = "Hack- & Makespace im Herzen von Friedrichshain, Bastelstube für Technikinteressierte + Raum für Netzpolitisches"
  defaultThumbnailPlaceholder = "img/thumbnailPlaceholder.png" #existiert noch
  favicon = "images/favicons/"

  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style = "green"

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io email
  email = "info@x-hain.de"

  name = "xHain hack+makespace"
  about_us = ""

  # Format dates with Go's time formatting
  date_Format = "2. January 2006"

  logo = "/images/xhain_logo_small.png"
  logo_small = "/images/xhain_logo_small.png"
  address = """Grünberger Str. 14 10243 Berlin"""
  latitude = "52.512815"
  longitude = "13.4493919"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable icon menu
[params.icon_menu]
    enable = true

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.hero]
    enable = true
    url = "/images/hero.jpg"
    # For more informtion take a look at the README.

[params.recent_posts]
    enable = true

[markup.goldmark.renderer]
  unsafe= true

