baseURL = "https://staging.x-hain.de"
title = "xHain hack+makespace"
canonifyurls = true
languageCode = "en-us"
defaultContentLanguage = "de"
DefaultContentLanguageInSubdir = "true"
MetaDataFormat = "yaml"

# Define the number of posts per page
paginate = 6

[permalinks]
  post = "/:year/:month/:slug/"

[params]
  author = "xHain hack+makespace"
  defaultKeywords = ["hackspace", "makerspace", "xhain"]
  defaultDescription = "Hack- & Makespace im Herzen von Friedrichshain, Bastelstube für Technikinteressierte + Raum für Netzpolitisches"
  email = "info@x-hain.de"
  latitude = "52.512815"
  longitude = "13.4493919"

[Permalinks]
    articles = "/blog/:year/:month/:day/:title/"

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[markup.goldmark.renderer]
  unsafe= true


###### TRANSLATIONS ######

[languages]
[languages.de]
weight = 1
languageName = "Deutsch"
contentDir = "content/de"
title = "xHain hack+makespace"

[languages.en]
weight = 2
languageName = "English"
contentDir = "content/en"
title = "xHain hack+makespace"

[languages.de.params.tools]
title = "Unsere tools"

[languages.en.params.tools]
title = "Our tools"

[languages.de.params.social]
title = "Wir sind auch auf"

[languages.en.params.social]
title = "Find us elsewhere"

[menu]

###### MAIN MENU ######

[[languages.de.menu.main]]
  weight = 5
  identifier = "blog"
  name = "Blog"
  url = "/blog"

[[languages.de.menu.main]]
  weight = 4
  identifier = "calendar"
  name = "Kalender"
  url = "/calendar"

[[languages.de.menu.main]]
  weight = 3
  identifier = "support"
  name = "Unterstützendes"
  url = "/support"

[[languages.de.menu.main]]
  weight = 2
  identifier = "about"
  name = "Über uns"
  url = "/about"

[[languages.en.menu.main]]
  weight = 5
  identifier = "blog"
  name = "Blog"
  url = "/blog"

[[languages.en.menu.main]]
  weight = 4
  identifier = "calendar"
  name = "Calendar"
  url = "/calendar"

[[languages.en.menu.main]]
  weight = 3
  identifier = "support"
  name = "Support"
  url = "/support"

[[languages.en.menu.main]]
  weight = 2
  identifier = "about"
  name = "About Us"
  url = "/about"

###### TOOLS MENU ######

[[languages.de.menu.tools]]
  weight = 1
  identifier = "wiki"
  name = "Wiki"
  url = "https://wiki.x-hain.de/"

[[languages.de.menu.tools]]
  weight = 2
  identifier = "rocketchat"
  name = "Chat"
  url = "https://chat.x-hain.de/home"

[[languages.en.menu.tools]]
  weight = 1
  identifier = "wiki"
  name = "Wiki"
  url = "https://wiki.x-hain.de/"

[[languages.en.menu.tools]]
  weight = 2
  identifier = "rocketchat"
  name = "Chat"
  url = "https://chat.x-hain.de/home"

###### SOCIAL MENU ######

[[languages.de.menu.social]]
  weight = 3
  identifier = "fediverse"
  name = "Fediverse"
  url = "https://chaos.social/@xHain_hackspace"

[[languages.de.menu.social]]
  weight = 4
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com/xHain_hackspace"

[[languages.de.menu.social]]
  weight = 5
  identifier = "youtube"
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCndtqJj4CxWpn2PDdBE6q8g"

[[languages.de.menu.social]]
  weight = 6
  identifier = "gitlab"
  name = "Gitlab"
  url = "https://gitlab.com/xHain-hackspace"

[[languages.de.menu.social]]
  weight = 7
  identifier = "github"
  name = "Github"
  url = "https://github.com/orgs/xHain-hackspace/"

[[languages.de.menu.social]]
  weight = 5
  identifier = "youtube"
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCndtqJj4CxWpn2PDdBE6q8g"

[[languages.en.menu.social]]
  weight = 3
  identifier = "fediverse"
  name = "Fediverse"
  url = "https://chaos.social/@xHain_hackspace"

[[languages.en.menu.social]]
  weight = 4
  identifier = "twitter"
  name = "Twitter"
  url = "https://twitter.com/xHain_hackspace"

[[languages.en.menu.social]]
  weight = 5
  identifier = "youtube"
  name = "Youtube"
  url = "https://www.youtube.com/channel/UCndtqJj4CxWpn2PDdBE6q8g"

[[languages.en.menu.social]]
  weight = 6
  identifier = "gitlab"
  name = "Gitlab"
  url = "https://gitlab.com/xHain-hackspace"

[[languages.en.menu.social]]
  weight = 7
  identifier = "github"
  name = "Github"
  url = "https://github.com/orgs/xHain-hackspace/"


###### FOOTER MENU ######

[[languages.de.menu.footer]]
  weight = 1
  identifier = "Contact"
  name = "Kontakt"
  url = "/contact"

[[languages.en.menu.footer]]
  weight = 1
  identifier = "Contact"
  name = "Contact"
  url = "/contact"

[[languages.de.menu.footer]]
  weight = 1
  identifier = "Privacy"
  name = "Datenschutz"
  url = "/privacy"

[[languages.en.menu.footer]]
  weight = 1
  identifier = "Privacy"
  name = "Privacy"
  url = "/privacy"
